### ISSUE TITLE
It's really hard to distinguish selected text by mouse with normal text 

### ISSUE THREAD

**Issue by huyvohcmc** [challenger-deep-theme/iterm#1]
<img width="1036" alt="screen shot 2018-05-24 at 1 40 17 am" src="https://user-images.githubusercontent.com/17645203/40444392-7c37cbee-5ef3-11e8-8330-fda71b364e70.png">

When I use the mouse to select some text, it's really hard to distinguish them, the only difference is selected text will change color to white. Can we make the background of the selected text to yellow like in the picture above (when I perform search for text - cmd + f in iterm2)?

**Comment by MaxSt** [comment]
Sorry for the late reply.
This should be fixed with https://github.com/challenger-deep-theme/iterm/commit/3ea95aac53d0b8827415ea835b401d9491be9e34.
